permalink: /:year:month:day/:title
url: https://godjoy.github.io/
baseurl: ""

# variables
name: 19971222.exe
description: S/W Developer, Joy's Blog
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

repository: godjoy/godjoy.github.io

gems:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
